# Generated by Django 5.1.2 on 2025-05-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident_ticket',
            name='contributing_factors',
            field=models.ManyToManyField(through='api.Incident_factor', to='api.contributing_factor'),
        ),
        migrations.AlterField(
            model_name='department_poc',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_pocc', to='api.department'),
        ),
        migrations.AlterField(
            model_name='incident_ticket',
            name='assigned_POC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department_poc'),
        ),
    ]
