# Generated by Django 5.1.2 on 2025-04-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
    ]
