# Generated by Django 5.1.2 on 2025-04-29 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributing_factor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=10)),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.designation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department_poc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Incident_Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('occurence_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('risk_level', models.CharField(max_length=20, null=True)),
                ('evidence', models.FileField(null=True, upload_to='')),
                ('assigned_POC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department_poc')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('requestor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Incident_factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contributing_factor')),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Incident_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
        migrations.AddField(
            model_name='incident_ticket',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incident_type'),
        ),
        migrations.CreateModel(
            name='Stake_holder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
