# Generated by Django 5.1.2 on 2025-04-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='designation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
